name: SMPTimerPlugin
version: 1.0.0
main: com.example.smptimer.SMPTimerPlugin
api-version: "1.21"
author: YourName
description: A plugin to manage SMP start timer with world border

commands:
  smp:
    description: Main SMP timer command
    usage: /smp start <minutes>
    permission: smptimer.admin

permissions:
  smptimer.admin:
    description: Allows using SMP timer commands
    default: op
  smptimer.move:
    description: Allows moving during countdown
    default: op
