name: SMPTimer
version: 1.0.0
main: com.example.smptimer.SMPTimerPlugin
api-version: "1.21"
author: Twicefear
description: A comprehensive SMP timer plugin with world border management
website: https://github.com/yourusername/smp-timer-plugin

commands:
  smp:
    description: Main SMP timer command
    usage: /smp <start|cancel|status|setspawn>
    aliases: [smptimer]
    permission: smptimer.admin

permissions:
  smptimer.*:
    description: All SMP Timer permissions
    default: op
    children:
      smptimer.admin: true
      smptimer.bypass: true
      
  smptimer.admin:
    description: Allows using SMP timer admin commands
    default: op
    
  smptimer.bypass:
    description: Bypass player freeze during countdown
    default: op
    children:
      smptimer.admin: true
